### PR TITLE
Testing deployment

### PR DESCRIPTION
**Pull request by Arstanley**

### CODE REVIEW

**Comment by jtsiva** [comment]
You still need to address some changes I requested above. I assume the under development page now replaces the error on the settings page?

You second commit is great: you said you updated to add the android platform and that's all you did. Your other commit message tells me nothing. You should have committed a lot more since you added a bunch of new code. This commit appears to add both the email checking functionality and the under development page?

**Comment by Arstanley** [comment]
Yes, the second commit only adds the android platform, and the first commit was for the email checking functionality and the under development page. 

Bo

**Comment by Arstanley** [comment]
I still need to fix the scout arrival study page, which now only displays the email address (It was for the purpose of testing), and I will finish that tomorrow.

**Comment by jtsiva** [comment]
Commit looks good. Now set the branch to push to the master channel instead of production. Also, please update the name and description in config.xml

**Comment by Arstanley** [comment]
OK, but I might have some problem resolving the merge conflicts

**Pull request merged**
